### ISSUE TITLE
SetUpdate and SetOp appear redundant [JIRA: CLIENTS-180]

### ISSUE THREAD

**Issue by macintux** [basho/riak-java-client#432]
Possible that both are needed, but they're virtually identical

**Comment by broach** [comment]
Testing - ignore

**Comment by alexmoore** [comment]
Yeah, this is the typical duplication between the "api" and "core" sections of the client. Most users would only ever touch the SetUpdate class though.

**Comment by alexmoore** [comment]
Going to close this one, they may look identical but they do have different purposes. The other datatypes follow this pattern as well (not saying it's a great pattern), but wouldn't be worth the effort to take out.
