### ISSUE TITLE
Migration to 2.x documentation is required. [JIRA: CLIENTS-181]

### ISSUE THREAD

**Issue by indykish** [basho/riak-java-client#454]
I see several packages refactored in 2.x with a new design. Hence customers code running 1.4.x  `riak-java-client` will break when they move to `2.x` driver.

Of-course 1.4.x driver still works great with 2.0 riak.  If the doc doesn't exists then customers would loose out on the awesome features like `range, bucket types` etc.

This is the list of compile failures I  fixed in the scala https://github.com/megamsys/scaliak.

* In 1.4.x from the `raw.*` package you can feed a `http or protobuf client`,
In `2.0`, it's just one client `RiakClient`

* `com.basho.riak.client.http.{RiakConfig, RiakClient}` is 
 `com.basho.riak.client.api.{RiakClient}`
 `RiakConfig` is removed

To create RiakClient 
```java
List<String> addresses = new LinkedList<String>();
addresses.add("192.168.1.1");
addresses.add("192.168.1.2");
addresses.add("192.168.1.3");
RiakClient client = RiakClient.newClient(addresses);
```

(or) with timeouts, connection config and such.

```java
List<String> addresses = new LinkedList<String>();
addresses.add("192.168.1.1");
addresses.add("192.168.1.2");
addresses.add("192.168.1.3");
RiakNode.Builder builder = new RiakNode.Builder()
                                        .withRemotePort(port)
                                        .withMinConnections(10);
        List<RiakNode> nodes = RiakNode.Builder.buildNodes(builder, remoteAddresses);
        RiakCluster cluster = new RiakCluster.Builder(nodes).build();
        cluster.start();
        return new RiakClient(cluster);

```

*`com.basho.riak.client.cap.VClock` is `com.basho.riak.client.api.cap.VClock`

*`BucketPropertiesBuilder` is now `BucketProperties.Builder`
 methods needs to be prefixed with `with` - camelcase

*`com.basho.riak.client.IRiakObject`, com.basho.riak.client.DefaultRiakObject is removed, instead use `com.basho.riak.client.core.query.RiakObject`
`getLastModified()` now returns `long`

*`FetchOperation.Builder.withNotFoundOK(boolean notFoundOk)` - Here the `K` is upper          cased.
 `BucketProperties.Builder.withNotFoundOk(boolean ok)` - Here `k` is lowercased. There needs to be a consistency.

*`com.basho.riak.client.http.Constants` is `com.basho.riak.client.core.util.{ Constants => RiakConstants }`

*`LinkwalkStep` is com.basho.riak.client.api.commands.mapreduce.{LinkPhase }
`LinkPhase needs to be public` 

*`com.basho.riak.IntIndex` nuked, is `com.basho.riak.client.core.query.indexes.{ RiakIndexes, LongIntIndex, StringBinIndex }`

*`com.basho.riak.client.query.LinkWalkStep.Accumulate` is removed.

*`com.basho.riak.client.raw.query.MapReduceSpec` is `com.basho.riak.client.api.commands.mapreduce.MapReduceSpec`

 *`FetchOperation.Builder withIfNotModified(byte[] vclock)` takes `Array[bytes]` as opposed to cap.VClock.

*`com.bash.riak.client.core.query.indexes.{IntValueQuery, BinValueQuery, IndexQuery}` is 
`com.basho.riak.client.api.commands.indexes. {IntIndexQuery, BinIndexQuery, SecondaryIndexQuery}`

*ping can be done on the `RiakCluster only`.
RiakClient should support a ping.

Still more errors to go. I am going to open issues for little api changes.

**Comment by broach** [comment]
testing - ignore

**Comment by Basho-JIRA** [comment]
Reviewed Alex's changes to add in depth upgrading info to the wiki for the Java client. Everything looks good. 

**_[posted via JIRA by Christopher Mancini]**_
