### ISSUE TITLE
RiakClient : ping wrapper method needed [JIRA: CLIENTS-24]

### ISSUE THREAD

**Issue by indykish** [basho/riak-java-client#456]
It would be nice to provide a wrapper method `ping` in `RiakClient` which calls `RiakCluster` ping. (or) 
getter for `cluster` in `RiakClient` unless there would more things folks want to control.

**Comment by broach** [comment]
The referenced PR should take care of this. 

Also note that you can do a spot check at any time now from the RiakClient via:

```
RiakCluster cluster = clientInstance.getRiakCluster();
List<RiakNode> nodes = cluster.getNodes();
for (RiakNode node : nodes)
{
    State state = node.getNodeState();
}
```
