### ISSUE TITLE
Java Client 1.4.4 - executeStreaming for FetchIndex does not retry on failure [JIRA: CLIENTS-848]

### ISSUE THREAD

**Issue by anrask** [basho/riak-java-client#459]
I'm using version 1.4.4 of the client and have configured it to run against a cluster of nodes with the ClusterClient. Because the client is configured with several nodes and retrying of operations switches node it leads to a good and fault tolerant system.

The problem is that when I fetch objects based on index using the executeStream function of FetchIndex, the operation is not retried when one of the nodes is unreachable. I can't tell if this is due to the design of streaming or just missing.

**Comment by alexmoore** [comment]
@anrask Is this still an issue for you, or have you upgraded to a 2.0 client?

**Comment by Basho-JIRA** [comment]
Won't fix, older version of Java Client. 

**_[posted via JIRA by Alexander Moore]**_
