### ISSUE TITLE
A sample code for ListKeys won't compile [JIRA: CLIENTS-46]

### ISSUE THREAD

**Issue by gitmako** [basho/riak-java-client#485]
Hello,

I tried to use ListKeys in version 2.0.0, but sample code (written in their Javadoc) won't compile.
It seems that a java compiler cannot find symbol for ListKeys.Builder.

My code is below.

```java
package com.example;

import com.basho.riak.client.api.RiakClient;
import com.basho.riak.client.api.commands.kv.ListKeys;
import com.basho.riak.client.core.query.Namespace;

public class App {

    public static void main(String[] args) throws Exception {

        // Just same as sample written in Javadoc
        Namespace ns = new Namespace("my_type", "my_bucket");
        ListKeys lk = ListKeys.Builder(ns).build();
        ListKeys.Response response = client.execute(lk);
        for (Location l : response)
        {
            System.out.println(l.getKeyAsString());
        }
    }

}
```

And, error message from mvn is below.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project riak-export: Compilation failure
[ERROR] /home/example/riak-export/src/main/java/com/example/App.java:[18,31] cannot find symbol
[ERROR] symbol:   method Builder(com.basho.riak.client.core.query.Namespace)
[ERROR] location: class com.basho.riak.client.api.commands.kv.ListKeys
```

I tried compile it using javac1.7.0.67 (osx 10.7 32bit) and javac1.8.0.25 (ubuntu 13.10 64bit), and result are same.

If there are any effective remedies, please tell me.

**Comment by broach** [comment]
The Java client currently buffers the entire result set (even though it's technically "streaming" from Riak) therefore if you're trying to list millions of keys ... yeah, probably not going to fly. 

Incorporating streaming to the user with Netty and async is tricky and a decision was made to leave it out of the 2.0 release of the Java client for that reason.  I am planning to add this but as of right now it's just not possible.

**Comment by Basho-JIRA** [comment]
Fixing at a later date, already planned. 

***[posted via JIRA by Brian Roach]***

**Comment by Basho-JIRA** [comment]
Reopening to get correct resolution status. 

**_[posted via JIRA by Derek Somogyi]**_
