### ISSUE TITLE
Not possible to search through key [JIRA: CLIENTS-76]

### ISSUE THREAD

**Issue by niedomnie** [basho/riak-java-client#486]
in BigIndexQuery.java in subclass Init, there is always appending BIN prefix, even if you want to search through $key, although such search is possible through HTTP
e.g. curl http://localhost:8098/types/type/buckets/bucket/index/\$key/start/end

in constructor indexName == $key should not be appended with anything or there should be another constructor without indexName e.g.
    public Init(Namespace namespace, S start, S end)
        {
            super(namespace, "$key", start, end);
        }

  protected static abstract class Init<S, T extends Init<S,T>> extends SecondaryIndexQuery.Init<S,T>
    {
        private Charset charset = Charset.defaultCharset();

        public Init(Namespace namespace, String indexName, S start, S end)
        {
            super(namespace, indexName + Type._BIN, start, end);
        }

        public Init(Namespace namespace, String indexName, S match)
        {
            super(namespace, indexName + Type._BIN, match);
        }

        T withCharacterSet(Charset charset)
        {
            this.charset = charset;
            return self();
        }

    }

PS. workaround for this is to rewrite class BinIndexQuery with relations
PS2. there is always problem with properties (used in SecondIndexQuery hierarchy) with package modifier (if there will be protected it was easier to override classes - less code to fix such issue)

**Comment by sebaes** [comment]
I have just hit this issue in the java client v2.0.1, I can see the issue is closed, but the codebase is not fixed AFAICT. Am I missing something or it just got lost?
Thanks.

**Comment by alexmoore** [comment]
Hi @sebaes, it looks like it was fixed with https://github.com/basho/riak-java-client/commit/1394884dcf2e793180ff880bc74ff8d2bb8b40d7,  do you have code to reproduce the issue?

**Comment by sebaes** [comment]
Hi @alexmoore, just checked and you are right, it is fixed. My confusion came from using BinIndexQuery (which always concatenate "_bin") instead of RawIndexQuery (which you can pass the Type on), copied from the examples http://docs.basho.com/riak/latest/dev/using/2i/
There were no examples or mention of RawIndexQuery, may be worth adding to the docs at some point?
Sorry for the noise, and thanks for your help!.
