### ISSUE TITLE
please cut a new release with bug fixes [JIRA: CLIENTS-283]

### ISSUE THREAD

**Issue by shtratos** [basho/riak-java-client#508]
Please cut a new Maven release which includes this fix:
https://github.com/basho/riak-java-client/pull/478

**Comment by broach** [comment]
@shtratos This was cut and released to Sonatype today. Should propagate to Maven Central in a few hours. I'll leave this open until I verify that has occurred.

**Comment by Basho-JIRA** [comment]
v2.0.1 has propagated to Maven Central

http://search.maven.org/#artifactdetails%7Ccom.basho.riak%7Criak-client%7C2.0.1%7Cjar 

**_[posted via JIRA by Brian Roach]**_

**Comment by shtratos** [comment]
Thanks a lot!
