### ISSUE TITLE
Sun Tools jar included with hardcoded path [JIRA: CLIENTS-310]

### ISSUE THREAD

**Issue by zero1zero** [basho/riak-java-client#512]
System dependency for tools.jar is set to: 

``` xml
    <dependency>
          <groupId>com.sun</groupId>
          <artifactId>tools</artifactId>
          <version>1.4.2</version>
          <scope>system</scope>
          <systemPath>/Library/Java/JavaVirtualMachines/jdk1.7.0_25.jdk/Contents/Home/jre/../lib/tools.jar</systemPath>
        </dependency>
    <dependency>
```

In version 2.0.1 of the riak-client library.  This explicitly fails for non-OSX machines and machines that don't have that specific version of the JDK.  For example, I am building on OSX but only have version 1.7.0_60 installed.

The full path should be replaced with `<systemPath>${java.home}/../lib/tools.jar</systemPath>` as explicitly mentioned in https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#System_Dependencies.

I know this was considered as part of #461, but that was closed with no resolution for some reason.

I would also note that the version specifies 1.4.2, which is confusing as the library doesn't appear to support <1.6.

**Comment by zero1zero** [comment]
I should note the workaround is to specify your riak-client dependency as:

``` xml
 <!-- riak module -->
 <dependency>
     <groupId>com.basho.riak</groupId>
     <artifactId>riak-client</artifactId>
     <version>${riak.version}</version>
     <exclusions>
        <exclusion>
            <groupId>com.sun</groupId>
            <artifactId>tools</artifactId>
        </exclusion>
     </exclusions>
 </dependency>
<dependency>
    <groupId>com.sun</groupId>
    <artifactId>tools</artifactId>
    <version>1.5.0</version>
    <scope>system</scope>
    <systemPath>${java.home}/../lib/tools.jar</systemPath>
</dependency>
```

**Comment by cosmin-marginean** [comment]
+1
As per comments here: https://github.com/basho/riak-java-client/issues/461
this doesn't seem to be essential, unless I'm missing something. However without the unfortunate workaround above, this doesn't work on our envs either (JDK 8, osx or otherwise)

**Comment by alexmoore** [comment]
@cosmin-marginean @zero1zero So tools.jar is needed for a custom Taglet that we use for documenting Thread safety:  https://github.com/basho/riak-java-client/blob/develop/src/main/java/com/basho/riak/client/javadoc/RiakThreadSafetyTaglet.java

I'm trying to see if there's a way around this right now, but the only way I've found so far is to ditch the taglet.

**Comment by zero1zero** [comment]
Does my proposed change (using the java.home property) work in lieu of the full path? I don't mind including tools.jar in my project, it just seems that the build should not fail when that path doesn't resolve.

**Comment by alexmoore** [comment]
@zero1zero It's that way in the pom.xml now:  https://github.com/basho/riak-java-client/blob/develop/pom.xml#L310, and it gets the hard path when it's built:

``` bash
cat ~/.m2/repository/com/basho/riak/riak-client/2.0.2-SNAPSHOT/riak-client-2.0.2-SNAPSHOT.pom
...
    <dependency>
      <groupId>sun.jdk</groupId>
      <artifactId>tools</artifactId>
      <version>1.5.0</version>
      <scope>system</scope>
      <systemPath>/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/../lib/tools.jar</systemPath>
    </dependency>
```

**Comment by cosmin-marginean** [comment]
If this jar is not needed at runtime then probably the Javadoc should be handled outside that pom.xml in some other way

The headache it causes outweighs the need to produce custom Javadoc taglets, in my opinion. 

My take is that if the library/framework/etc can be used at runtime without a dependency then that jar is not really a dependency from a system's perspective, hence one should be able to build their app without it

Cheers
Cos

**Comment by alexmoore** [comment]
Hey @cosmin-marginean & @zero1zero,

I've thought about it and I will take it out in one of the next releases.  I'll have to work a replacement in for that thread safety taglet to keep the documentation, but it shouldn't be hard just tedious. 

For now you should be able to get around it by adding an exclusion to your `pom.xml` file:

``` xml
        <dependency>
            <groupId>com.basho.riak</groupId>
            <artifactId>riak-client</artifactId>
            <version>2.0.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sun</groupId>
                    <artifactId>tools</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

Thanks,
Alex

**Comment by jeacott** [comment]
was this actually fixed somewhere? closed with no ref of how or why is very unhelpful. this is definitely a pita problem.

**Comment by alexmoore** [comment]
Hi @jeacott, this was fixed on the develop branch, and should be out with the next release (today or next week).
