### ISSUE TITLE
Difficult to mock when unit testing [JIRA: CLIENTS-520]

### ISSUE THREAD

**Issue by jplock** [basho/riak-java-client#526]
Right now, none of the API classes implement `equals`, `hashCode` or `toString()` which makes mocking and comparing them to mocked copies difficult.  Would you accept a pull request to implement these methods in at least `RiakCommand` but others may be required?

**Comment by alexmoore** [comment]
Sure! PRs with good ideas are always welcome.

**Comment by jplock** [comment]
sure thing, I'll submit one

**Comment by alexmoore** [comment]
This was merged into the develop branch, and should be out with the next release (today or next week).

**Comment by stela** [comment]
See also #557, which in the same spirit adds equals(), hashCode() and toString() methods to RiakObject and dependent classes. This is useful when mocking out RiakClient.
