### ISSUE TITLE
Source is using JDK7 items, when target is 1.6 [JIRA: CLIENTS-521]

### ISSUE THREAD

**Issue by jplock** [basho/riak-java-client#527]
Currently in the pom, the maven-compiler-plugin says the source and target are `1.6`, however Eclipse complains about two usages of JDK7 code in the codebase:
- https://github.com/basho/riak-java-client/blob/develop/src/main/java/com/basho/riak/client/api/RiakClient.java#L265 - `getHostString() is not visible`
- https://github.com/basho/riak-java-client/blob/develop/src/test/java/com/basho/riak/client/core/fixture/NetworkTestFixture.java#L20 - `java.net.StandardSocketOptions` was introduced in JDK7

I guess we could fix this by either increasing the minimum version to `1.7` or find JDK6 equivalents.

**Comment by alexmoore** [comment]
Hey @jplock, not sure how this slipped past - we have the animal sniffer plugin enabled but something's not obviously working.

**Comment by alexmoore** [comment]
Ok, this was fixed on the the above PR, and should be out with the next release (today or next week).
