### ISSUE TITLE
In-Heap caching, Cache API and JCache support [JIRA: CLIENTS-532]

### ISSUE THREAD

**Issue by cruftex** [basho/riak-java-client#534]
As a KV-store it would be great if standard Java APIs could be supported, e.g. the JCache API

Background: I am working on http://cache2k.org and plan to integrate Riak as a secondary storage provider. This will be a big technical challenge.

The idea of this issue is to get some more opinions on it and see what directions make sense. In particular:
- How this complements the existing java client? Is JCache something that is planed within the Riak client?
- What is the benefit? Is there a (technical) use case? E.g. porting/migrating JCache based applications on Riak
- Areas where there is an "impedance mismatch" and how to overcome this
- do applications use in-heap caching, like Google Guava on top of the Riak java client?

**Comment by alexmoore** [comment]
Hi @cruftex,

This is the first JCache request I've heard so I'll try my best.

> How this complements the existing java client? Is JCache something that is planed within the Riak client?

JCache is not something that's planned, we love to see community involvement though! As far as complementing the client, it sounds like it would be a library that uses the Riak Java client as a dependency, not an addition to the client.   We do have a Redis add-on coming to Riak in the future, but that's to be a cache to Riak itself: http://basho.com/products/redis/.

> What is the benefit? Is there a (technical) use case? E.g. porting/migrating JCache based applications on Riak

Not sure, you made the request :)  One benefit would be scaling your cache safely more than Redis or other implementations could. Porting applications would be another, like you said.

> Areas where there is an "impedance mismatch" and how to overcome this?

One area where you would run into a mismatch would be the notion of [siblings / conflict resolution](http://docs.basho.com/riak/latest/dev/using/conflict-resolution/), which is a side effect of being eventually consistent and distributed.  Eventual consistency + being distributed aren't a bad thing, they allow us to scale much more than other DB's, you just have to work with the trade offs.   

These tradeoffs do conflict with some of the JCache spec though:

```
2.3.1. Default Consistency
When using the default consistency mode, most cache operations are performed as if a locking
mechanism exists for each key in a Cache. When a cache operation acquires an exclusive read and
write lock on a key all subsequent operations on that key will block until that lock is released. The
consequences are that operations performed by a thread happen-before read or mutation operations
performed by another thread, including threads in different Java Virtual Machines.
This can be understood as a pessimistic locking approach. Lock, mutate and unlock.
```

(Java™ Caching API - JSR107 Expert Group - Dec 16, 2013)

Most of the operations rely on these CAS operations, so any implementation wouldn't hold up to the spec 100%.  You could use `last-write-wins` (and possibly lose data), or [write a conflict resolver for your classes](http://docs.basho.com/riak/latest/dev/using/conflict-resolution/java/) to get around siblings/conflicts though, but you will have to know about the trade offs. 

> Do applications use in-heap caching, like Google Guava on top of the Riak java client?

Possibly, but I've not heard of it being used like this before. 

Does this answer your questions?

Thanks,
Alex
