### ISSUE TITLE
NullPointerException in hashCode of commands [JIRA: CLIENTS-550]

### ISSUE THREAD

**Issue by sebaes** [basho/riak-java-client#535]
After commit:
d5c0a1b700e1fccf660feab2384c19840b57616b

There are missing checks in hashCode methods.
For example class: StoreValue

```
    result = prime * result + typeReference.hashCode();
```

If command was built without typeReference that line throws an exception when you add this command to a Map structure for example.

Thanks!

**Comment by alexmoore** [comment]
Fixed with 95399f.

**Comment by alexmoore** [comment]
Fixed with 95399ffffa0fa4ab371c1d449114852eb582b352.
