### ISSUE TITLE
Detect non-existing keys for CRDTs [JIRA: CLIENTS-552]

### ISSUE THREAD

**Issue by TimurFayruzov** [basho/riak-java-client#536]
There is a semantic difference between non-existing key and a default value may me important for downstream consumers. However, CRDT queries return default values: 0 for a counter and empty set for a set. My following examples are in Scala:

```
val fetchOp = new FetchCounter.Builder(location).build()
val c = client.execute(fetchOp).getDatatype // if I get 0, does the key exist in store?
```

For counters, there is a workaround that involves an additional query:

```
val fetchOp = new FetchValue.Builder(location).withOption(FetchValue.Option.HEAD, java.lang.Boolean.TRUE).build()
val res = client.execute(fetchOp) // res.isNotFound should equal(true). 
// Why isNotFound not supported by CRDTs?
```

For sets, there seem to be a hack that a context object should be null if set did not exist before (not sure if it's a valid way though).

The concept of non-existing key is important enough to support it explicitly (like with regular objects in the snippet above).

**Comment by alexmoore** [comment]
So another way around this for now is to set the "NotFoundOK" option on the command/operation to false, and then check the status of the future when it returns.   

``` java
Location location = new Location(new Namespace(mapBucketType, bucketName), "404");
DtFetchOperation fetch = new DtFetchOperation.Builder(location).withNotFoundOK(false).build();
final RiakFuture<DtFetchOperation.Response, Location> future = cluster.execute(fetch);

future.await();
assertFalse(future.isSuccess()); // isSuccess = false because notFound is not ok
assertNotNull(future.get()); // Still returns new object.
```

If you set `.withNotFoundOK(false)`, the `isSuccess()` property should be false for a "new" dataType, but future.get() will still return the new datatype object.

**Comment by alexmoore** [comment]
Digging into the implementation a little more today:

https://github.com/basho/riak_pb/blob/develop/src/riak_dt.proto#L113-L132

> When the `value` field is missing from the message, the client should interpret it as a "not found".

Right now we just grab the value without seeing if it's there or not, which gives us the default value that the PB lib provides:  https://github.com/basho/riak-java-client/blob/3699bc05c041a5add92223907c50fbe3005a5d7b/src/main/java/com/basho/riak/client/core/converters/CrdtResponseConverter.java#L102-L121

I'll add a "notFound" parameter to the response object and check that property.
