### ISSUE TITLE
Tomcat deployment [JIRA: CLIENTS-556]

### ISSUE THREAD

**Issue by mxt33** [basho/riak-java-client#538]
Is it safe to use this project within Tomcat (and Spring)? My main concern surrounds the use of ScheduledThreadPoolExecutor. Will these threads be container managed? Can it hooked in with CommonJ?

Thanks

Mark

**Comment by alexmoore** [comment]
Hi Mark, 

The ScheduledThreadPoolExecutor is used to handle a thread per connection, as well as others for the Retry queue worker. Netty also has it's own threads, but those are in Netty's pool.  

If you want to use a `ScheduledExecutorService` that is provided through Tomcat or CommonJ you can pass that in as an argument to the `RiakCluster` builder: http://basho.github.io/riak-java-client/2.0.1/com/basho/riak/client/core/RiakCluster.Builder.html#withExecutor(java.util.concurrent.ScheduledExecutorService)

Just ensure you have ([`MaxConnections`](http://basho.github.io/riak-java-client/2.0.1/com/basho/riak/client/core/RiakNode.Builder.html#DEFAULT_MAX_CONNECTIONS) per Node) \* (Number of RiakNodes you configured) + 2 threads available for the client in the pool. 

Does this answer your question?

Thanks,
Alex
