### ISSUE TITLE
The RiakIndex annotation should not have a default value [JIRA: CLIENTS-559]

### ISSUE THREAD

**Issue by empovit** [basho/riak-java-client#540]
The _RiakIndex_ annotation requires an index name to function properly, therefore it does not make sense for it to have a default value (especially if it is an empty string). Replacing  

``` java
String name() default "";
```

with

``` java
String name();
```

will cause compilation errors whenever the annotation is used without an index name. The validation for empty string in _AnnotationUtils_ should remain in place.

**Comment by empovit** [comment]
Submitted a pull request for this bug.

**Comment by alexmoore** [comment]
Merged the PR into develop, thanks!
