### ISSUE TITLE
Remove 'final' from RiakCommand classes [JIRA: CLIENTS-598]

### ISSUE THREAD

**Issue by mxt33** [basho/riak-java-client#546]
The use of 'final' within RiakCommand class names makes it difficult to Mock/Stub these classes with Spock.

For example:

public final class FetchValue

I'd like to stub this object but cannot because it is 'final.

**Comment by alexmoore** [comment]
Hi @markandirene,

We originally marked them as `final` to seal the low-level details up, but I can see the need to mock them as well.  It looks like others have [run into this limitation with Spock as well](https://code.google.com/archive/p/spock/issues/333). Have you tried using [PowerMock with Spock](http://stackoverflow.com/questions/19493690/using-powermock-with-spock/24749047#24749047) to get around it? 

Thanks,
Alex

**Comment by alexmoore** [comment]
Closing issue, no response.
