### ISSUE TITLE
Cannot perform a count using Search.Builder [JIRA: CLIENTS-599]

### ISSUE THREAD

**Issue by mxt33** [basho/riak-java-client#547]
groovy:

riakClient.execute(new Search.Builder('myindex', 'lastName:smith').withRows(0).build()).getAllResults()

The withRows(0) statement is ignored.

I'd like to just return a count of the objects, rather than a results list.

**Comment by Basho-JIRA** [comment]
Fixed in https://github.com/basho/riak-java-client/pull/594 

**_[posted via JIRA by Alexander Moore]**_
