### ISSUE TITLE
java.io.IOException: An existing connection was forcibly closed by the remote host [JIRA: CLIENTS-600]

### ISSUE THREAD

**Issue by mxt33** [basho/riak-java-client#548]
I'm using a shared RiakClient (Spring bean) and am seeing a number of exceptions in my error log:

java.io.IOException: An existing connection was forcibly closed by the remote host

The application appears to continue normally but I'm concerned about these exceptions. What is causing these exceptions?

**Comment by lukebakken** [comment]
Are there errors that happen at the same time in Riak's logs? `/var/log/riak/error.log*` is a good place to start.

**Comment by alexmoore** [comment]
Hi @markandirene,

Were you able to correlate these messages with any errors on Riak's logs?

It could be as simple as Riak or your load balancer was just killing off connections for some reason.

**Comment by alexmoore** [comment]
Hi @markandirene,

Were you able to correlate these messages with any errors on Riak's logs?
Did you have any other information for this issue?

Thanks,
Alex
