### ISSUE TITLE
Duplicated charset when storing a RiakObject with a content type with charset [JIRA: CLIENTS-602]

### ISSUE THREAD

**Issue by gfbett** [basho/riak-java-client#549]
If I store a RiakObject with a content type of `application/json;charset=UTF-8`, the charset gets duplicated on the stored value when read by http, ending up with this content type:
`application/json;charset=UTF-8; charset=UTF-8`

I did a small sample to show the issue here: 
https://github.com/gfbett/RiakIssueSample

**Comment by alexmoore** [comment]
Few issues here actually:
1. When we manually set a `charset` on the RiakObject, it actually goes onto the `content-type` [[0](https://github.com/basho/riak-java-client/blob/9fe8a45c2398a102ab8f3a6156ad14ef67b72df9/src/main/java/com/basho/riak/client/core/query/RiakObject.java#L272-L276)].
2. When we convert the RiakObject to the ProtocolBuffer wire format, it will grab the `charset` off of the `content-type` buffer, but it won't remove it  [[1](https://github.com/basho/riak-java-client/blob/3699bc05c041a5add92223907c50fbe3005a5d7b/src/main/java/com/basho/riak/client/core/converters/RiakObjectConverter.java#L146-L153)].  This is where we get the duplicate `UTF-8`.
3. When we convert from the ProtocolBuffer wire format back to a RiakObject, the charset gets put back onto the `content-type` [[2](https://github.com/basho/riak-java-client/blob/3699bc05c041a5add92223907c50fbe3005a5d7b/src/main/java/com/basho/riak/client/core/converters/RiakObjectConverter.java#L67-L75)], but de-dupes it in the process [[3](https://github.com/basho/riak-java-client/blob/8ca0b8e633b6925936b079987b69ce27626c8018/src/main/java/com/basho/riak/client/core/util/CharsetUtils.java#L139-L145)].

Also, according to the IETF, `charset` isn't a real optional parameter to the `application/json` content-type:

> Note:  No "charset" parameter is defined for this registration.
>    Adding one really has no effect on compliant recipients.

  http://www.iana.org/assignments/media-types/application/json

With that, we should stop putting the charset on the content-type automatically.  If the user includes it in both fields, it will be duplicated by Webmachine (As seen in the reproducer).  If they put each value in each field respectively, it should come out as expected in Webmachine.
