### ISSUE TITLE
Superfluous declarations of UnknownHostException [JIRA: CLIENTS-614]

### ISSUE THREAD

**Issue by christopherfrieler** [basho/riak-java-client#552]
The constructors of RiakCluster and RiakNode and the corresponding Builders' build()-methods declare the UnknownHostException. But I don't see a way how this exception can occur. May it be that these declarations are superfluous? This might relate to https://github.com/basho/riak-java-client/pull/519.

**Comment by alexmoore** [comment]
Yeah, that looks like a vestigial piece of code that was originally in the RiakNode constructor and branched it's way out.  We only need UnknownHostException on RiakNode's `start` & `buildNodes`  functions, and RiakCluster's `addNode` I think.  I'll cut those declared ones out of the constructors this week sometime for the next release, unless you'd like to submit a PR for them :)

Thanks!

**Comment by alexmoore** [comment]
Also I think the idea was originally we'd check to see if the host was viable when we first created the node, but we just left that up to `start` for api design reasons.

**Comment by christopherfrieler** [comment]
Added pull request to fix this.

**Comment by alexmoore** [comment]
Fixed with the merge of #553
