### ISSUE TITLE
ListBuckets ignores bucket type, lists buckets of type "default" [JIRA: CLIENTS-654]

### ISSUE THREAD

**Issue by empovit** [basho/riak-java-client#565]
ListBuckets ignores the bucket type member, so that the command works for "default" only.

**Comment by empovit** [comment]
Fixed by pull request https://github.com/basho/riak-java-client/pull/566

**Comment by alexmoore** [comment]
Thanks again for the PR.

**Comment by Basho-JIRA** [comment]
Fixed by pull request #566 

**_[posted via JIRA by Alexander Moore]**_
