### ISSUE TITLE
Feature Request: ability to get Riak Objects as Java streams. [JIRA: CLIENTS-656]

### ISSUE THREAD

**Issue by jeacott** [basho/riak-java-client#570]
Coming from OpenStack Swift where I can:
InputStream dataStream = storedObject.downloadObjectAsInputStream();

it seems like a significant missing API that could serve to reduce memory requirements accessing/processing large objects.

would be nice to have.

**Comment by empovit** [comment]
Would be great to have indeed. That said, changes in the Riak KV core are required to my understanding.

**Comment by alexmoore** [comment]
@jeacott What would you define as a "large object" in this case? We typically tell people to keep object sizes in the 10KB - 100KB range.

**Comment by jeacott** [comment]
I'd like to use Riak for images, probably up to 1mb, most much less, and for xml documents which could be zipped to be of the same order, both of which would benefit from the ability to read/process as streams. Ive used riak in the past for short string storage and its so much easier to manage than swift (and its not written in python) I'd much prefer to use it, but the lack of streaming options makes me doubt its suitability for my case.

**Comment by jeacott** [comment]
Being able to stream objects into Riak would also be quite helpful!
when I have all my larger content referenced as streams, running into a line like this isn't ideal:
riakObject.setValue(BinaryValue.create(IOUtils.toByteArray(myInputStream)));

has anyone tried JOSS (http://joss.javaswift.org) against the RiakCS openstack API? it wouldn't be using the protobuf api, but it would at least stream at the client end.

**Comment by alexmoore** [comment]
This would be super nice, but we'd have to redo how the server side sends data to do it.  

I'm going to close this for now, but I'll keep it in mind if we ever get to such a point. 

Thanks,
Alex

**Comment by jeacott1** [comment]
well there go a bunch of usecases I'd have preferred riak for.

**Comment by lukebakken** [comment]
@jeacott - there's no reason that objects can't be fetched into byte array streams if streaming is an absolute requirement.

If you could elaborate on your use cases that _absolutely require streaming_ we may be able to give you ideas on implementation.

> I'd like to use Riak for images, probably up to 1mb, most much less, and for xml documents which could be zipped to be of the same order, both of which would benefit from the ability to read/process as streams

Since these object fit within Riak's recommended size of 1MiB, I would fetch them as needed into in-memory streams, and do your stream processing that way.
