### ISSUE TITLE
Scala cannot access private inner classes, making Indexes nearly impossible to instantiate [JIRA: CLIENTS-689]

### ISSUE THREAD

**Issue by TJC** [basho/riak-java-client#584]
The current recommended way of getting an index is something like:

riakObj.getIndexes.getIndex( StringBinIndex.Name("example") )

Except that the .Name class within StringBinIndex cannot be accessed from Scala, and that is not going to change.

Making the .Name class and constructors on RiakIndexes public would sort this out.

**Comment by Basho-JIRA** [comment]
Here is a code snippet we are using in Spark Connector [link link|https://github.com/basho/spark-riak-connector/blob/develop/test-utils/src/main/scala/com/basho/riak/spark/rdd/RiakFunctions.scala#L124-L143]

 

***[posted via JIRA by Sergey Galkin]***

**Comment by Basho-JIRA** [comment]
Here is a code snippet we are using in Spark Connector [link link|https://github.com/basho/spark-riak-connector/blob/develop/test-utils/src/main/scala/com/basho/riak/spark/rdd/RiakFunctions.scala#L124-L143]. It might be a good idea for me to review 2i java client implementation for the discrepancies

**_[posted via JIRA by Sergey Galkin]**_

**Comment by TJC** [comment]
Hi Sergey, that setup of parameterised getIndex() with the Index.named() constructor (instead of the Index.Name() constructor) was how I managed to get it to work in the end.
However the documentation seems to prefer the Index.Name() constructor.

**Comment by alexmoore** [comment]
@TJC What documentation preferred the Index.Name() constructor?  I can put in a fix for that if I can find it.

**Comment by TJC** [comment]
It's been over a month.. took me a while to find it again.
http://imgur.com/wMDiue1
(The javadoc for the riak client seems kinda sucky -- the URL doesn't contain the info needed to get back to the page it's actually displaying)

**Comment by Basho-JIRA** [comment]
fix is included on the https://github.com/basho/riak-java-client/tree/scala-improvements branch 

**_[posted via JIRA by Alexander Moore]**_
