### ISSUE TITLE
Best Practice for Indexing Protobuf for Search [JIRA: CLIENTS-696]

### ISSUE THREAD

**Issue by vchan-acm** [basho/riak-java-client#587]
Hi, is there a best practice for indexing java protobuf's for search?

I have a List of objects that need to be searched on. Is there a way we can search a specific field of that object?

ie. 

message Video { 
  // ...
  VideoMetadata videoMetadata = 2;
}

message VideoMetadata {
  // ...
  TagCollection tag_collection = 9; 
}

message TagCollection {
  repeated Tag tags = 1;
}

message Tag {
  // id of the tag
  string id = 1;

  // name of the tag
  string name = 2;

  // number of occurances of the tag
  int64 count = 3;
}

I would like to be able to search for Videos that have a specific tag name.

Thanks

**Comment by alexmoore** [comment]
Hi @vchan-acm,

I'm not sure this is possible, as SOLR would have to be able to break down the protobuf schema/messages.  If your data was saved in a more open format like XML or JSON it would be trivial.  You can give it a try by looking into the [Schema docs for SOLR](https://wiki.apache.org/solr/SchemaXml) but I don't think this isn't something SOLR can do OOTB.

Thanks,
Alex
