### ISSUE TITLE
2.0.5 in maven central? [JIRA: CLIENTS-796]

### ISSUE THREAD

**Issue by jplock** [basho/riak-java-client#600]
I noticed that 2.0.5 was created, but I don't see any packages in Maven Central.  Were they published?  Thanks!

**Comment by alexmoore** [comment]
Yep, it should be there.  I wonder if MC is having trouble updating their search indices. 

http://search.maven.org/#artifactdetails%7Ccom.basho.riak%7Criak-client%7C2.0.5%7Cjar
http://repo1.maven.org/maven2/com/basho/riak/riak-client/2.0.5/

**Comment by jplock** [comment]
Awesome, thanks!
