### ISSUE TITLE
Question on properly implementing a conflict resolver [JIRA: CLIENTS-797]

### ISSUE THREAD

**Issue by jplock** [basho/riak-java-client#601]
In the `GameLeaderboardResolver` as mentioned in https://github.com/basho/riak-java-client/wiki/Fetching-Data-from-Riak-%28v2.0%29#gameleaderboardresolverjava, it does the following:

``` java
GameLeaderboard resolvedLeaderboard = new GameLeaderboard(i.next());
```

If I'm understanding this correctly, that will create a new `GameLeaderboard` instance with an empty `@RiakVClock` annotation, which is then returned.

Is this correct?  I was under the assumption that an object should be returned which contains an existing vclock reference to be used as the proper resolved object from a list of siblings.  Or maybe it doesn't matter?

**Comment by empovit** [comment]
@jplock Have a look at `getValue()` of [KvResponseBase.java](https://github.com/basho/riak-java-client/blob/develop/src/main/java/com/basho/riak/client/api/commands/kv/KvResponseBase.java). First, a correct value is resolved using a resolver. Then, a field annotated with `@RiakVClock` is populated with the right VClock using `AnnotationUtil.setVClock()` before returning the resolved value to a client. Does it answer your question?

**Comment by jplock** [comment]
Yes it does, thanks.  So regardless if you have an object with an existing vclock or not, the vclock from the first sibling will be set on the resolved sibling.  Thanks!
