### ISSUE TITLE
Add a client timeout for synchronous command execution [JIRA: CLIENTS-818]

### ISSUE THREAD

**Issue by bwittwer** [basho/riak-java-client#609]
Hello,

The synchronous execute method() in the RiakCommand is actually a wrapper around the asynchronous executeAsync() method.  But it has no possibility to specify a timeout on the underlying Future.

As the future.get() is currently done without any timeout this might result in calling thread hanging forever if the future is never resolved (for whatever reason).

To allow isolating the caller thread from the internal retry and pooling mechanism of the client, we propose to add another execute() to the RiakCommand and RiakClient with the timeout.

Thanks.
Kind regards.
Bernard.

**Comment by jplock** [comment]
Don't most of the KV commands already expose a timeout option in the request builders?

**Comment by jplock** [comment]
Or I guess that's a server side timeout, not client side

**Comment by bwittwer** [comment]
The command timeout is the Riak-side timeout. It will be sent to Riak as part of the PB message (example: https://github.com/basho/riak_pb/blob/develop/src/riak_kv.proto#L56). 
Here the proposal is a pure client-side timeout: if a connection to Riak is in progress or established when a node shutdowns, it might results in them not being handled nicely.

**Comment by angrycub** [comment]
This was closed by https://github.com/basho/riak-java-client/pull/642 which extended https://github.com/basho/riak-java-client/issues/610 with test cases.  Thanks @bwittwer
