### ISSUE TITLE
Riak TS may return msg code 0 even when TTB specified [JIRA: CLIENTS-839]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-java-client#616]
Test:
- Enable Riak Security
- Try a Riak TS Query using TTB, but don't specify auth or to use security
- Riak will return msg code 0 and the "please STARTTLS message" in a PB-encoded RiakError

**Comment by alexmoore** [comment]
We handle this in the Java client already, we read the reply message code and act according to that instead of expecting one format or another.
