### ISSUE TITLE
Handle bare 'tsqueryresp' atoms [JIRA: CLIENTS-844]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-java-client#618]
Test:
- Riak TS
- Write test that executes `CREATE TABLE` via TTB encoded `tsqueryreq`
- Ensure bare atom response of `tsqueryresp` is handled

basho/riak-python-client#469

**Comment by alexmoore** [comment]
Back in your court, check out   09ee18f.

**Comment by alexmoore** [comment]
+1'd by Luke
