### ISSUE TITLE
Add support bucket index [JIRA: CLIENTS-879]

### ISSUE THREAD

**Issue by tomaszszlek** [basho/riak-java-client#622]
Hi, 
I would like to use $bucket secondary index using java riak client.
I have noticed that such possibility was added some time ago in:  #129.
It seems that in current version we can't use $bucket index in Java client (I am using client ver. 2.1.4).
In documentation there is a note that we can use it via REST API: [http://docs.basho.com/riak/kv/2.1.4/developing/usage/secondary-indexes/#retrieve-all-bucket-keys-via-the-bucket-index](url)
but there is no example how to do it in java.
The old code, which was added in #129 look like follows:
`
final Bucket b = riakClient.fetchBucket(bucketName).execute();
all = b.fetchIndex(BucketIndex.index).withValue("_").execute();
`

**Comment by alexmoore** [comment]
Hi @tomaszszlek,

You can do a $bucket index query with:

``` java
RawIndexQuery biq  =
            new RawIndexQuery.Builder(namespace, "$bucket", Type._BUCKET, bucketName)
                .withKeyAndIndex(true).build();
```

https://github.com/basho/riak-java-client/blob/32f898e756025cacdae2ff353a350b90118e970b/src/test/java/com/basho/riak/client/api/commands/indexes/itest/ITestRawIndexQuery.java#L144-L146

It is a little duplicative, so I'll see if we can make a streamlined command in the future.

**Comment by alexmoore** [comment]
Hi @tomaszszlek,

I had a few free hours so I made a set of specialized [$bucket](https://github.com/basho/riak-java-client/blob/d0c19a1dacbbbca577fe362be83c8c453c28bb36/src/main/java/com/basho/riak/client/api/commands/indexes/BucketIndexQuery.java) and [$key](https://github.com/basho/riak-java-client/blob/d0c19a1dacbbbca577fe362be83c8c453c28bb36/src/main/java/com/basho/riak/client/api/commands/indexes/KeyIndexQuery.java) index commands, and they should be much more straightforward to use.   Look for them in the next release!

Thanks,
Alex
