### ISSUE TITLE
How to specify a custom convertor in Riak 2.x client ? [JIRA: CLIENTS-880]

### ISSUE THREAD

**Issue by preetamr** [basho/riak-java-client#623]
Hi,

-Sorry for posting on the issues wiki since I could not figure out the right forum for java riak client 2.x?

-While profiling with flight recorder, I see that about 20% of time is spent in Jackson from within Riak client (Fetch/Store). Our app is heavy on Riak, using about 40+ Riak calls per request in some specific complex apis that I was testing.

-Can you please let me know how can I try out alternate convertors and benchmark ? 1.x seemed to have a way as per docs, but not in 2.x.

Thanks
Preetam

**Comment by alexmoore** [comment]
Hi Preetam,

The 2.0 Converters work similar to the 1.0 converters.  You'll [extend an abstract `Converter<T>`](https://github.com/basho/riak-java-client/blob/3699bc05c041a5add92223907c50fbe3005a5d7b/src/test/java/com/basho/riak/client/api/convert/ConverterFactoryTest.java#L136-L174) class, and then [register it with the ConverterFactory](https://github.com/basho/riak-java-client/blob/3699bc05c041a5add92223907c50fbe3005a5d7b/src/test/java/com/basho/riak/client/api/convert/ConverterFactoryTest.java#L125-L127), which tells the client to use that converter for that type. 

You can annotate fields in your POJOs with our [available annotations](http://basho.github.io/riak-java-client/2.0.6/com/basho/riak/client/api/annotations/package-summary.html), just the same as 1.0. 

Let me know if you need more help.

Thanks,
Alex

**Comment by preetamr** [comment]
Thanks Alex for the quick response. I will try it out.
