### ISSUE TITLE
No node awareness for riak clients [JIRA: CLIENTS-882]

### ISSUE THREAD

**Issue by arunvisw** [basho/riak-java-client#624]
Currently HttpClusterPoolClient does not know whether all the hosts in the hosts list are up and running. If by chance a node goes down, it will keep trying that host everytime a new request gets in. So for example is the timeout on the http client is 10 seconds, then we will waste 10 seconds of our time by just trying the host which is down. We need to have a heartbeat mechanism for riak clients which will continuously monitor whether the hosts are up and when it detects that a host is down, it needs to quarantine that client till the host becomes active again.

**Comment by arunvisw** [comment]
I have coded this up and i can submit a pull request soon

**Comment by alexmoore** [comment]
Hi @arunvisw,

The 2.0 client has heartbeats, node health, etc built-in.  What version are you running?

Thanks,
Alex

**Comment by arunvisw** [comment]
1.4.4... the problem is we are using 1.4.2 riak and cannot use the new 2.0 client which is not backward compatible..

**Comment by arunvisw** [comment]
@alexmoore

**Comment by lukebakken** [comment]
@arunvisw both Riak 1.4.2 and Riak Java client 1.4.4 are no longer supported. We appreciate your offer of a PR but can't accept it due to the old Riak Java client no longer being supported.

Riak Java clients 2.0 and later _are_ compatible with Riak 1.4.X versions, however, so that may be an option for you.

Thanks

**Comment by Basho-JIRA** [comment]
Won't fix, for an older version of the Java Client. 

**_[posted via JIRA by Alexander Moore]**_
