### ISSUE TITLE
java.io.IOException: An existing connection was forcibly closed by the remote host  [JIRA: CLIENTS-891]

### ISSUE THREAD

**Issue by pradheeps** [basho/riak-java-client#627]
I run riak java client 2.0.4 in Windows and RHEL against riak server 2.0.6. I get the below error only in Windows and sometimes i see puts and get fail when this happens. Any reason as why this happens and any possible fix available?

ERROR [nioEventLoopGroup-3-3:]  com.basho.riak.client.core.RiakNode - Operation onException() channel: id:414833480 <riak node>:8087 java.io.IOException: An existing connection was forcibly closed by the remote host

**Comment by alexmoore** [comment]
Hi @pradheeps,  

We've received your GitHub Issue and ZenDesk ticket.  The issue you are seeing is that a network connection was forcibly closed by the Riak server, Load Balancer, or something in between your client and host. The client will take care of this case, so there is nothing for you, the user, to do.  If this happens often you may have a bad piece of hardware. 

You should also see another log message that indicates what was happening with this connection at the time it was closed.  If the log message says "inAvailable channel closed", then the connection was not being used at the time. If it was being used you'll see another log message from the RiakNode class, and the client's retry logic should retry the operation on a different node/connection until it succeeds or runs out of retries.  

I've also opened an issue(#628) to downgrade the severity of that log message, as it is an expected occasional state. 

Thanks,
Alex

**Comment by alexmoore** [comment]
Hi @pradheeps,   

We haven't heard back so I'm going to close this ticket.  If you were able to find more information about the order of events in your logs, please reopen it.

Thanks,
Alex

**Comment by Basho-JIRA** [comment]
Need more information to decide if it's a bug or a user error. 

**_[posted via JIRA by Alexander Moore]**_
