### ISSUE TITLE
RiakClient.Delete issue [JIRA: CLIENTS-898]

### ISSUE THREAD

**Issue by InfoTrendsGit** [basho/riak-java-client#630]
Cannot delete if using RiakClient.Delete(IEnumerable<RiakObjectId> riakObjectIds)

But Delete works fine if using RiakClient.Delete(RiakObjectId riakObjectIds)

**Comment by alexmoore** [comment]
Hi, could you provide the following information?
- [ ] Riak Java Client version
- [ ] Java version
- [ ] Riak version
- [ ] Operating System / Distribution & Version
- [ ] Riak `error.log` file, if applicable
- [ ] Sample data, if applicable

**Comment by InfoTrendsGit** [comment]
Sorry. Yes, it is .NET RiakClient. It does work if deleting a "collection of RiakObjectId". But it does work if delete individual RiakObjectId

**Comment by alexmoore** [comment]
This issue was moved to basho/riak-dotnet-client#310
