### ISSUE TITLE
Ending support for Java 7 [JIRA: CLIENTS-919]

### ISSUE THREAD

**Issue by alexmoore** [basho/riak-java-client#635]
Now that we are[ 1 year past the Java 7 End of Public Updates](http://www.oracle.com/technetwork/java/eol-135779.html), we should end support for it.  Moving to Java 8 will give us some nice code features too.

**Comment by cvitter** [comment]
Have we polled users/customers about dropping Java 7 support? I wonder how many are still using Java 7 (or even 6).

**Comment by alexmoore** [comment]
True, but Java 7 doesn't get security updates either, so it may not be in the customer's best interest to develop new products on older JRE's.  I'll ping the mailing list to see if a majority objects or agrees.

**Comment by alexmoore** [comment]
@cvitter Also I killed off 6 support last year, and have heard 0 complaints.

**Comment by guidomedina** [comment]
I always say: Screw older versions but some industries for no apparent reason stay stuck with Java 6 and 7 but IMHO, thumbs up (reflected on the 1st comment)
