### ISSUE TITLE
2i Queries with Coverage Context Aren't Built Correctly [JIRA: CLIENTS-961]

### ISSUE THREAD

**Issue by alexmoore** [basho/riak-java-client#658]
I started with a test failure: 

> ITestCoveragePlan: fetchAllDataByUsingCoverageContext -> get null pointer exception on [this line](https://github.com/basho/riak-java-client/blob/05fbe31620495feea9f33bc3138132bad0e6cf79/src/test/java/com/basho/riak/client/core/operations/itest/ITestCoveragePlan.java#L157-L157)

And realized the 2i Coverage Context queries weren't including either a match or a range, so need to expand the api to cover that. 

Reference: 

[Context with match](https://github.com/basho/riak-erlang-client/blob/b4a188aa528d8f418e2634549f21c21739a7642f/src/riakc_pb_socket.erl#L1039-L1056)

[Context with Range](https://github.com/basho/riak-erlang-client/blob/b4a188aa528d8f418e2634549f21c21739a7642f/src/riakc_pb_socket.erl#L1092-L1116)

**Comment by alexmoore** [comment]
Don't need this just yet, but will in the future.

**Comment by srgg** [comment]
@alexmoore The idea was to do not overcomplicate Query Builders by introducing a specific constructor for for each possible case, therefore by using as an example BinQuery:

here is constructors available for Builder in  BinIndexQuery:

creation with Range:
https://github.com/basho/riak-java-client/blob/develop/src/main/java/com/basho/riak/client/api/commands/indexes/BinIndexQuery.java#L188

creation with exact match:
https://github.com/basho/riak-java-client/blob/develop/src/main/java/com/basho/riak/client/api/commands/indexes/BinIndexQuery.java#L204

creation with coverage context:
https://github.com/basho/riak-java-client/blob/develop/src/main/java/com/basho/riak/client/api/commands/indexes/BinIndexQuery.java#L171

Usage of CoverageContext in conjunction with range or match requires to constructor a builder by using specific constructor for
range or exact match and then to provide coverage context by using this method:
  https://github.com/basho/riak-java-client/blob/develop/src/main/java/com/basho/riak/client/api/commands/indexes/SecondaryIndexQuery.java#L523 

please let me know if I missed something or you have objections/concerns

**Comment by alexmoore** [comment]
Nope, looks good.  I think I was a little confused at first how to build the match/range + coverage queries, but that straightens it out.  Just need to document it then once we start pushing coverage more.

**Comment by Basho-JIRA** [comment]
This was fixed for the 2.0.7 release.  

**_[posted via JIRA by Alexander Moore]**_
