### ISSUE TITLE
Netty 4.1.3 has a regression that is fixed in 4.1.4+ [JIRA: CLIENTS-978]

### ISSUE THREAD

**Issue by randysecrist** [basho/riak-java-client#670]
Riak Java Client version 2.0.7 uses Netty 4.1.3.

http://netty.io/news/2016/07/27/4-0-40-Final-4-1-4-Final.html

The above indicates there is a memory usage regression and that upgrade should happen as soon as possible.  Further review of 4.1.5 as well may be the best target.

**Comment by alexmoore** [comment]
Fixed in #671.
