### ISSUE TITLE
Getting error "Unknown message code: 11" during get object from Riak [JIRA: CLIENTS-1018]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-java-client#681]
Original issue: basho/riak#879

```
com.basho.riak.client.core.netty.RiakResponseException: Unknown message code: 11
at com.basho.riak.client.core.netty.RiakResponseHandler.channelRead(RiakResponseHandler.java:52) ~[com.basho.riak.riak-client-2.0.5.jar:na]
at
```

**Comment by lukebakken** [comment]
@AliakseiMat - can you please provide the version of the following software you're using?
- Riak
- Riak Java Client

**Comment by AliakseiMat** [comment]
Riak-java-client: 2.0.5
Riak: 2.1.3
So, we got those errors during data migration process and huge numbers of read/write requests was triggered. Thanks!

**Comment by lukebakken** [comment]
Can you provide more information about this data migration process? Are you using a proxy server in your environment?

**Comment by lukebakken** [comment]
Were any Riak nodes shut down or did any crash during this process?

**Comment by AliakseiMat** [comment]
No, we have 9 nodes, each running on separate ec2 and the separate machine for the server itself (only one server node was involved in migration). No one node was crashed when those errors occurred.

**Comment by AliakseiMat** [comment]
After re-migrating for the tenants who had those errors, every things went fine.

**Comment by lukebakken** [comment]
The "Unknown message code" error can happen when a Riak node is starting up or shutting down and the API hasn't fully initialized. I doubt you will see this error again. If you do, please re-open this issue.

**Comment by AliakseiMat** [comment]
Ohh, I see. So, since Riak possibly auto-recovered that why we didn't see any nodes down.

**Comment by alexmoore** [comment]
Yep, and if the Java client saw an error response it should have retried
the command up to 3 times total on different connections.  Do you run with
the built-in LB or do you use an external one like Nginx, F5, etc?

**Comment by AliakseiMat** [comment]
Yes, we have LB in front of all our 9 nodes. Got it, thanks!

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
