### ISSUE TITLE
Change an F to an R as a typo fix [JIRA: CLIENTS-1038]

### ISSUE THREAD

**Issue by genericProgramming** [basho/riak-java-client#686]
## Context
FiakFutureListener isn't a thing, but RiakFutureListener is.

## Expected Behavior
A user should read 'RiakFutureListener' in the javadoc

## Actual Behavior
A user reads 'FiakFutureListener' in the javadoc, and is subsequently so confused that they decide to give up writing code and become a 'scrum master'.

## Possible Fix
Someone else makes the change from an F to an R

## Steps to Reproduce
1. Look at the docs

## Context
I chuckled, and then opened this issue/PR. Then, after all of this typing for a one letter change, I also questioned my ability to properly manage time.

## Your Environment
- [ 2.0.7] Riak Java Client version
- [8 ] Java version
- [ ] Riak version
- [ ] Operating System / Distribution & Version
- [ ] Riak's `error.log` file, if applicable
- [ ] What methods were being executed during the error
- [ ] What you *expected* to have happen
- [ ] Sample data, if applicable

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
