### ISSUE TITLE
execute never responds [JIRA: CLIENTS-1072]

### ISSUE THREAD

**Issue by jackhelper** [basho/riak-java-client#699]
Running through tutorials and doing a simple "hello world" insert into a test bucket using python client and curl works just fine.  Do the same using java client and the store operation never returns.  Specifically getting stuck on .await() in Futures.

Here is the code:
`
           
        	RiakClient client = RiakClient.newClient(8098, "192.168.1.189");

            Namespace ns = new Namespace("default", "my_bucket");
            Location location = new Location(ns, "my_key");
            RiakObject riakObject = new RiakObject();
            riakObject.setValue(BinaryValue.create("my_value"));
            StoreValue store = new StoreValue.Builder(riakObject)
              .withLocation(location)
              .withOption(Option.W, new Quorum(3)).build();
            client.execute(store);
            
            // Now that we're all finished, we should shut our cluster object down
            client.shutdown();

`

**Comment by alexmoore** [comment]
Hi Jack,

In your example you'll want to use the port for the Protocol Buffers interface, which is 8087 by default:
```
RiakClient client = RiakClient.newClient(8087, "192.168.1.189");
```
`8098` is the port for Riak's HTTP interface, which the Java client doesn't support. 

Thanks,
Alex

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
