### ISSUE TITLE
Is the Riak java client still active?

### ISSUE THREAD

**Issue by busbey** [basho/riak-java-client#720]
I'm a maintainer on the YCSB project and I'm attempting to do a pass updating the various data store bindings we have in the project.

We have a riak KV binding but it hasn't really been updated since Apr 2016. It looks like the latest riak java client artifacts in maven central are also from 2016.

Is there a different maven repository I should point folks towards for a more recent release? Is there an updated release planned?

**Comment by martinsumner** [comment]
The riak clients no longer have any active support.  The riak database continues to be supported and developed as an open source produce, just not the clients.

The new versions of Riak should remain backwards compatible with the old versions of the client, it is just new features which will be unavailable.

**Comment by busbey** [comment]
thanks for the answer!
